on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Identify
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
      - name: test
        run: |
          touch test.txt
          git add test.txt
          git commit -m "test"
          git push origin HEAD:main
